version: "3.7"

x-aws-vault-environment: &aws-vault-environment
  - AWS_VAULT
  - AWS_DEFAULT_REGION
  - AWS_REGION
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - AWS_SECURITY_TOKEN
  - AWS_SESSION_EXPIRATION

services:
  infra:
    build: .
    volumes:
      - .:/infra
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    environment: *aws-vault-environment
